"""The hosted build: the same app, as an installable web app (spec §8).

Jugni's output is one self-contained file that opens from `file://` with the
network off. A PWA is the opposite shape — a manifest, a service worker and an
icon, each fetched by URL from a secure origin. They cannot be the same
artifact, so this is an *additional* output rather than a change to the
existing one: `trips/<slug>/jugni.html` stays byte-for-byte what it was, and
`trips/<slug>/hosted/` is what you upload.

Everything here is generated from the app's own design tokens so the install
screen, the splash colour and the icon cannot drift from the app they open.
"""

from pathlib import Path

# Straight from src/css/01-tokens.css. Duplicated deliberately and narrowly:
# a manifest is read by the OS before any CSS is parsed, so these two values
# have to exist outside the stylesheet. Everything else stays in the tokens.
LIGHT_BG, LIGHT_BRASS = "#EDEEE7", "#96661F"
DARK_BG, DARK_BRASS = "#101416", "#D6A65B"

ICON_PX = 180          # Apple's recommended apple-touch-icon size
SAFE = 0.60            # maskable icons get cropped to a circle; keep the mark
                       # inside the middle 60% or Android clips it


def colours(theme: str) -> tuple[str, str]:
    """(background, accent) for the trip's own theme."""
    return (DARK_BG, DARK_BRASS) if theme == "dark" else (LIGHT_BG, LIGHT_BRASS)


def icon_svg(theme: str = "light") -> str:
    """The compass mark, drawn rather than borrowed.

    Full-bleed background so Android's adaptive mask has something to crop
    into, with the needle inside the safe circle so nothing is lost when it
    does. Kept in sync with `icon_png` below by hand — two renderers, one
    shape, and it is simple enough that a divergence is obvious.
    """
    bg, mark = colours(theme)
    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" role="img" aria-label="Jugni">
  <rect width="100" height="100" fill="{bg}"/>
  <circle cx="50" cy="50" r="30" fill="none" stroke="{mark}" stroke-width="3" opacity="0.35"/>
  <path d="M50 22 L60 50 L50 78 L40 50 Z" fill="{mark}"/>
  <path d="M50 22 L60 50 L50 50 Z" fill="{mark}" opacity="0.55"/>
  <circle cx="50" cy="50" r="4" fill="{bg}"/>
</svg>
"""


def icon_png(theme: str = "light", size: int = ICON_PX) -> bytes:
    """The same mark as a PNG, for iOS.

    `apple-touch-icon` does not accept SVG — given one, Safari silently falls
    back to a screenshot of the page, which looks like a bug rather than a
    brand. This is the only raster asset in the project, drawn with Pillow
    (already a dependency for OCR) rather than adding an SVG rasteriser.
    """
    from PIL import Image, ImageDraw

    bg, mark = colours(theme)
    scale = 4                                    # draw big, downsample smooth
    n = size * scale
    img = Image.new("RGB", (n, n), bg)
    d = ImageDraw.Draw(img)
    c = n / 2
    r = n * SAFE / 2

    d.ellipse([c - r, c - r, c + r, c + r], outline=mark, width=max(2, int(n * 0.012)))
    needle = [(c, c - r * 0.94), (c + r * 0.34, c), (c, c + r * 0.94), (c - r * 0.34, c)]
    d.polygon(needle, fill=mark)
    d.ellipse([c - n * 0.04, c - n * 0.04, c + n * 0.04, c + n * 0.04], fill=bg)

    return img.resize((size, size), Image.LANCZOS)


def manifest(trip_name: str, theme: str) -> str:
    import json
    bg, brass = colours(theme)
    return json.dumps({
        "name": trip_name or "Jugni",
        "short_name": (trip_name or "Jugni").split()[0][:12],
        "description": "Your trip, in one place — offline-first.",
        # Relative, not "/index.html": a hosted trip may well live at a
        # subpath, and an absolute start_url breaks the install there with no
        # error anyone will see until they tap the icon.
        "start_url": "./index.html",
        "scope": "./",
        "display": "standalone",
        "orientation": "any",
        "background_color": bg,
        "theme_color": brass,
        "icons": [
            {"src": "icon.svg", "sizes": "any", "type": "image/svg+xml"},
            {"src": "icon.svg", "sizes": "any", "type": "image/svg+xml", "purpose": "maskable"},
            {"src": f"icon-{ICON_PX}.png", "sizes": f"{ICON_PX}x{ICON_PX}", "type": "image/png"},
        ],
    }, indent=2) + "\n"


def service_worker(build_id: str) -> str:
    """Cache-first over the app shell.

    The cache name carries the build id, so a redeploy is a new cache and the
    old one is deleted on activate. Bumping it by hand — which the upstream
    instructions asked for — is exactly the step everyone forgets, and the
    symptom is a returning user pinned to a stale app with no way to tell.
    """
    return f"""/* Generated by `make host`. Do not edit — rebuild instead. */
const CACHE = 'jugni-{build_id or "shell"}';
const SHELL = ['./', './index.html', './manifest.webmanifest', './icon.svg', './icon-{ICON_PX}.png'];

self.addEventListener('install', (event) => {{
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)));
  self.skipWaiting();
}});

self.addEventListener('activate', (event) => {{
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
}});

self.addEventListener('fetch', (event) => {{
  /* Only GETs, and only this origin. A POST or a cross-origin call — the
     weather and currency APIs — must reach the network or fail honestly,
     never be answered from a cache that cannot hold them. */
  if (event.request.method !== 'GET') return;
  if (new URL(event.request.url).origin !== self.location.origin) return;

  event.respondWith(
    caches.match(event.request).then((hit) => hit || fetch(event.request).catch(() => {{
      /* Offline and not in the cache: hand back the shell so a deep link
         still opens the app rather than the browser's error page. */
      if (event.request.mode === 'navigate') return caches.match('./index.html');
      throw new Error('offline');
    }}))
  );
}});
"""


HEAD = """<link rel="manifest" href="manifest.webmanifest">
<link rel="apple-touch-icon" href="icon-{px}.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="{short}">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="theme-color" content="{brass}">"""


def head_tags(trip_name: str, theme: str) -> str:
    _, brass = colours(theme)
    return HEAD.format(px=ICON_PX, brass=brass,
                       short=(trip_name or "Jugni").split()[0][:12])


def write(out_dir: Path, html: str, trip_name: str, theme: str, build_id: str) -> list[str]:
    """Write the hosted bundle. Returns the filenames, for the build log."""
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "index.html").write_text(html, encoding="utf-8")
    (out_dir / "manifest.webmanifest").write_text(manifest(trip_name, theme), encoding="utf-8")
    (out_dir / "sw.js").write_text(service_worker(build_id), encoding="utf-8")
    (out_dir / "icon.svg").write_text(icon_svg(theme), encoding="utf-8")
    icon_png(theme).save(out_dir / f"icon-{ICON_PX}.png", "PNG", optimize=True)
    return ["index.html", "manifest.webmanifest", "sw.js", "icon.svg", f"icon-{ICON_PX}.png"]


# Injected into the hosted copy only. A service worker needs a secure origin,
# so this can never run from file:// — but `navigator.serviceWorker` still
# *exists* there, and an unguarded register() rejects with an uncaught error in
# the console of the very file we promise works offline. Hence the catch.
REGISTER = """<script>
(function () {
  if ('serviceWorker' in navigator && location.protocol !== 'file:') {
    addEventListener('load', function () {
      navigator.serviceWorker.register('./sw.js').catch(function () {
        /* Not a secure origin, or the user blocks workers. The app still runs;
           it just is not installable here. */
      });
    });
  }
  /* Ask the browser not to evict this trip during routine housekeeping. It is
     a request, not a guarantee — iOS in particular may still clear it under
     storage pressure — so it layers on top of Trip data → Export, which
     remains the only actual backup. */
  if (navigator.storage && navigator.storage.persist) {
    navigator.storage.persist().then(function (granted) {
      console.info('Jugni: persistent storage ' + (granted ? 'granted' : 'not granted'));
    }).catch(function () {});
  }
}());
</script>"""
